name: ubunturdp
on: 
  workflow_dispatch:
   inputs:
     auth:
        description: 'GRDP Authorization Code'
        required: true
        default: 'paste your code here'
  
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Update Environment
      run: | sudo apt-get update && sudo apt-get upgrade

    - name:  Install XRDP

run: sudo apt install xrdp

- name: Check status of XRDP: ( XRDP runs automatically after installation)

run: sudo systemctl status xrdp


- name: add the xrdp user to the ssl-cert group

run: sudo adduser xrdp ssl-cert  

- name: Restart xrdp service:

run: sudo systemctl restart xrdp

- name: Configuring Firewall
Xrdp daemon listens on port 3389. You must open the Xrdp port if your Ubuntu server is protected by a firewall.

run: sudo ufw allow from 192.168.33.0/24 to any port 3389


run: sudo ufw allow 3389

--------------------------------
Connecting to the Xrdp Server
-------------------------------
The default RDP client is accessible if you have a Windows PC.
Enter "remote" in the Windows search box and click on "Remote Desktop Connection". 
The RDP client will open as a result. 
Enter the IP address of the remote server in the "Computer" field and click "Connect".

On the login screen, enter your username and password before clicking on “OK.”



---------------------------------
Xrdp Configuration : FOR UNDERSTANDING ONLY
---------------------------------
The directory /etc/xrdp contains the Xrdp configuration files. You do not need to modify the configuration files for simple Xrdp connections.

Xrdp uses the default X Window desktop environment (Gnome or XFCE).

xrdp.ini is the main configuration file. This file is divided into sections and lets you set global configuration settings such as security and listening addresses, as well as create separate Xrdp login sessions.

You must restart the Xrdp service after making any configuration file changes.

To start an X session, Xrdp uses the startwm.sh file. Edit this file if you want to use a different X Window desktop.



-----------------------------------------
IMPORTANT: Multi User Setup Configuration
-----------------------------------------
- name: Install D-BUS

run: sudo apt-get update
run: sudo apt-get upgrade 
run: sudo apt-get install dbus-x11


2. modify your /etc/xrdp/startwm.sh file

run: sudo nano /etc/xrdp/startwm.sh

At the below line before this line test -x /etc/X11/Xsession && exec /etc/X11/Xsession.

ADD THESE LINES

run: export $(dbus-launch)

Then save the file.

3. Restart the System: 

run: sudo reboot



----------------------
REFERENCES:
----------------------
https://vegastack.com/tutorials/how-to-install-xrdp-server-on-ubuntu-22-04/
https://devicetests.com/fix-xrdp-login-blank-screen-issues
https://bonguides.com/black-screen-remote-desktop-to-ubuntu-from-windows-with-xrdp/
http://c-nergy.be/blog/?p=12043





